<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.11">
  <POU Name="PRG_Cycle" Id="{944d4077-7520-43a4-9286-0335fef2c8f2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Cycle
VAR	
Status : INT := 0;
bHomingDone: BOOL;
fbRTrigStart: INT;
END_VAR]]></Declaration>
    <Implementation>
      <SFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCImplementationObject">
              <o n="Root" t="SFCSegment">
                <o n="ElementList" t="SFCElementList">
                  <l2 n="InnerList">
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">310L</v>
                          <v n="IdParent">309L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">311L</v>
                          <v n="IdParent">309L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">312L</v>
                          <v n="IdParent">309L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">313L</v>
                          <v n="IdParent">309L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">314L</v>
                          <v n="IdParent">309L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">315L</v>
                          <v n="IdParent">309L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">316L</v>
                          <v n="IdParent">309L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">317L</v>
                          <v n="IdParent">309L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">318L</v>
                          <v n="IdParent">309L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">319L</v>
                          <v n="IdParent">309L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">320L</v>
                          <v n="IdParent">309L</v>
                        </o>
                      </l2>
                      <v n="Id">309L</v>
                      <v n="IdParent">5L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Init__to__Homing_step"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">322L</v>
                          <v n="IdParent">321L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">323L</v>
                          <v n="IdParent">321L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">324L</v>
                          <v n="IdParent">321L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">325L</v>
                          <v n="IdParent">321L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">326L</v>
                          <v n="IdParent">321L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">327L</v>
                          <v n="IdParent">321L</v>
                        </o>
                      </l2>
                      <v n="Id">321L</v>
                      <v n="IdParent">5L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Homing_step"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">298L</v>
                          <v n="IdParent">297L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">299L</v>
                          <v n="IdParent">297L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">300L</v>
                          <v n="IdParent">297L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">301L</v>
                          <v n="IdParent">297L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"TRUE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">302L</v>
                          <v n="IdParent">297L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">303L</v>
                          <v n="IdParent">297L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">304L</v>
                          <v n="IdParent">297L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">305L</v>
                          <v n="IdParent">297L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aHoming_step_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">306L</v>
                          <v n="IdParent">297L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">307L</v>
                          <v n="IdParent">297L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">308L</v>
                          <v n="IdParent">297L</v>
                        </o>
                      </l2>
                      <v n="Id">297L</v>
                      <v n="IdParent">5L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Homing_step__to__Cycle_Megagenial_step"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"bHomingDone"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">235L</v>
                          <v n="IdParent">234L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">236L</v>
                          <v n="IdParent">234L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">237L</v>
                          <v n="IdParent">234L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">238L</v>
                          <v n="IdParent">234L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">239L</v>
                          <v n="IdParent">234L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">240L</v>
                          <v n="IdParent">234L</v>
                        </o>
                      </l2>
                      <v n="Id">234L</v>
                      <v n="IdParent">5L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" />
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Cycle_Megagenial_step"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">242L</v>
                          <v n="IdParent">241L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">243L</v>
                          <v n="IdParent">241L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">244L</v>
                          <v n="IdParent">241L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">245L</v>
                          <v n="IdParent">241L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">246L</v>
                          <v n="IdParent">241L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">247L</v>
                          <v n="IdParent">241L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">248L</v>
                          <v n="IdParent">241L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">249L</v>
                          <v n="IdParent">241L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"_aCycle_Megagenial"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">250L</v>
                          <v n="IdParent">241L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">251L</v>
                          <v n="IdParent">241L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">252L</v>
                          <v n="IdParent">241L</v>
                        </o>
                      </l2>
                      <v n="Id">241L</v>
                      <v n="IdParent">5L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Cycle_Megagenial_step__to__Init"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"TRUE"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">114L</v>
                          <v n="IdParent">113L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">115L</v>
                          <v n="IdParent">113L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">116L</v>
                          <v n="IdParent">113L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">117L</v>
                          <v n="IdParent">113L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">118L</v>
                          <v n="IdParent">113L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">119L</v>
                          <v n="IdParent">113L</v>
                        </o>
                      </l2>
                      <v n="Id">113L</v>
                      <v n="IdParent">5L</v>
                    </o>
                    <o t="SFCJump">
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">29L</v>
                          <v n="IdParent">28L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">30L</v>
                          <v n="IdParent">28L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">31L</v>
                          <v n="IdParent">28L</v>
                        </o>
                      </l2>
                      <v n="Id">28L</v>
                      <v n="IdParent">5L</v>
                    </o>
                  </l2>
                </o>
                <l2 n="Attributes" cet="SFCAttribute">
                  <o>
                    <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">25L</v>
                    <v n="IdParent">5L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">26L</v>
                    <v n="IdParent">5L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <o n="Value" t="BoolValue">
                      <v n="Value">"FALSE"</v>
                      <v n="DefaultValue">"FALSE"</v>
                    </o>
                    <v n="Id">27L</v>
                    <v n="IdParent">5L</v>
                  </o>
                </l2>
                <v n="Id">5L</v>
                <v n="IdParent">-1L</v>
              </o>
              <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Identifier">"Specific"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Element type specific properties"</v>
                </o>
                <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Identifier">"Actions"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Action definitions"</v>
                </o>
                <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Identifier">"Common"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Common properties"</v>
                </o>
                <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Identifier">"Times"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Time definitions"</v>
                </o>
              </d2>
              <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">true</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                  <v n="Identifier">"Exclude"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Exclude this element from build"</v>
                </o>
                <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                  <v n="Identifier">"Parallel"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the branch to parallel mode"</v>
                </o>
                <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                  <v n="Identifier">"Name"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Name of the element"</v>
                </o>
                <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                  <v n="Identifier">"Duplication"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                </o>
                <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                  <v n="Identifier">"InitStep"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the step as the initial step"</v>
                </o>
                <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                  <v n="Identifier">"MainAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is active"</v>
                </o>
                <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">true</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                  <v n="Identifier">"Comment"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Comment of the element"</v>
                </o>
                <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                  <v n="Identifier">"Monitoring"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Indicates transition monitoring setting."</v>
                </o>
                <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                  <v n="Identifier">"ExitAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                </o>
                <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                  <v n="Identifier">"EntryAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is activated"</v>
                </o>
                <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                  <v n="Identifier">"MaxTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the maximal active time for the step"</v>
                </o>
                <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                  <v n="Identifier">"Symbol"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Symbol configuration setting of the element"</v>
                </o>
                <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                  <v n="Identifier">"MinTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the minimal active time for the step"</v>
                </o>
                <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                  <v n="Identifier">"Qualifier"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Qualifier of the action association"</v>
                </o>
              </d2>
              <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                <o>
                  <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Variable"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"Variable"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Call"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Call"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
                <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                <o>
                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"Unspecified"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"Unspecified"</v>
                    </o>
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Read"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Read"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Write"</v>
                      <v n="Value">3L</v>
                      <v n="Key">"Write"</v>
                    </o>
                    <o>
                      <v n="Identifier">"ReadWrite"</v>
                      <v n="Value">4L</v>
                      <v n="Key">"ReadWrite"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
              </d2>
              <v n="ImplId">2266L</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
            <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
            <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
            <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
            <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
            <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
            <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
            <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
            <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
            <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
            <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
            <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
          </TypeList>
        </XmlArchive>
      </SFC>
    </Implementation>
    <Action Name="_a_aHoming_Rail1_step_active" Id="{fb25f31f-f5aa-42a2-b0c0-7d19b1068d98}">
      <Implementation>
        <ST><![CDATA[Status := F_IssueActuatorCommand(sDevice := 'Motor1', bArg := TRUE);
]]></ST>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="_a_aHoming_Rail2_step_active" Id="{05de02ac-fc4f-4dfa-bf73-dd333619d594}">
      <Implementation>
        <ST><![CDATA[Status := F_IssueActuatorCommand(sDevice := 'Motor2', bArg := TRUE);
]]></ST>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="_a_aHoming_Rail3_step_active" Id="{a8079511-f2ba-46af-a200-391749389f5a}">
      <Implementation>
        <ST><![CDATA[Status := F_IssueActuatorCommand(sDevice := 'Motor3', bArg := TRUE);
]]></ST>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="_a_aHoming_Rail4_step_active" Id="{1a90254e-196a-43a6-a57f-623383978a9d}">
      <Implementation>
        <ST><![CDATA[Status := F_IssueActuatorCommand(sDevice := 'Motor4', bArg := TRUE);
]]></ST>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="_aCatch_Cell_Rail1" Id="{06e8ca90-ee36-400c-a2c7-f6476c6539a8}">
      <Implementation>
        <ST><![CDATA[Status := F_IssueActuatorCommand(sDevice := 'Chariot1', bArg := TRUE);

]]></ST>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="_aCycle_Megagenial" Id="{f41558d6-b881-4947-8649-a53b5a957e0e}">
      <Implementation>
        <SFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="SFCImplementationObject">
                <o n="Root" t="SFCSegment">
                  <o n="ElementList" t="SFCElementList">
                    <l2 n="InnerList">
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init__aCycle_Megagenial"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">4L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">5L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">6L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">7L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">8L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">9L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">10L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">11L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">12L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">13L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">14L</v>
                            <v n="IdParent">3L</v>
                          </o>
                        </l2>
                        <v n="Id">3L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Init__aCycle_Megagenial__to__Catch_Cell_Rail1_step"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"NOT bStopCycleMem"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">88L</v>
                            <v n="IdParent">87L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">89L</v>
                            <v n="IdParent">87L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">90L</v>
                            <v n="IdParent">87L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">91L</v>
                            <v n="IdParent">87L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">92L</v>
                            <v n="IdParent">87L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">93L</v>
                            <v n="IdParent">87L</v>
                          </o>
                        </l2>
                        <v n="Id">87L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Catch_Cell_Rail1_step"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">76L</v>
                            <v n="IdParent">75L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">77L</v>
                            <v n="IdParent">75L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">78L</v>
                            <v n="IdParent">75L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">79L</v>
                            <v n="IdParent">75L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">80L</v>
                            <v n="IdParent">75L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">81L</v>
                            <v n="IdParent">75L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">82L</v>
                            <v n="IdParent">75L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">83L</v>
                            <v n="IdParent">75L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_aCatch_Cell_Rail1"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">84L</v>
                            <v n="IdParent">75L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">85L</v>
                            <v n="IdParent">75L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">86L</v>
                            <v n="IdParent">75L</v>
                          </o>
                        </l2>
                        <v n="Id">75L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Catch_Cell_Rail1_step__to__Move_Rail1_step"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Status = 1 AND NOT bStopCycleMem"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">69L</v>
                            <v n="IdParent">68L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">70L</v>
                            <v n="IdParent">68L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">71L</v>
                            <v n="IdParent">68L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">72L</v>
                            <v n="IdParent">68L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">73L</v>
                            <v n="IdParent">68L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">74L</v>
                            <v n="IdParent">68L</v>
                          </o>
                        </l2>
                        <v n="Id">68L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Move_Rail1_step"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">65L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">66L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">67L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">37L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">38L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">39L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">40L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">41L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_aMove_Rail1"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">42L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">43L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">44L</v>
                            <v n="IdParent">64L</v>
                          </o>
                        </l2>
                        <v n="Id">64L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Move_Rail1_step__to__Drop_Cell_Rai1_step"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Status = 1 AND NOT bStopCycleMem"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">46L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">47L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">48L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">49L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">50L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">51L</v>
                            <v n="IdParent">45L</v>
                          </o>
                        </l2>
                        <v n="Id">45L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Drop_Cell_Rai1_step"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">53L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">54L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">55L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">56L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">57L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">58L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">59L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">60L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_aDrop_Cell_Rail1"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">61L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">62L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">63L</v>
                            <v n="IdParent">52L</v>
                          </o>
                        </l2>
                        <v n="Id">52L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Drop_Cell_Rai1_step__to__Init__aCycle_Megagenial"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"NOT bStopCycleMem"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">31L</v>
                            <v n="IdParent">30L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">32L</v>
                            <v n="IdParent">30L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">33L</v>
                            <v n="IdParent">30L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">34L</v>
                            <v n="IdParent">30L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">35L</v>
                            <v n="IdParent">30L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">36L</v>
                            <v n="IdParent">30L</v>
                          </o>
                        </l2>
                        <v n="Id">30L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCJump">
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init__aCycle_Megagenial"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">23L</v>
                            <v n="IdParent">22L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">24L</v>
                            <v n="IdParent">22L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">25L</v>
                            <v n="IdParent">22L</v>
                          </o>
                        </l2>
                        <v n="Id">22L</v>
                        <v n="IdParent">2L</v>
                      </o>
                    </l2>
                  </o>
                  <l2 n="Attributes" />
                  <v n="Id">2L</v>
                  <v n="IdParent">-1L</v>
                </o>
                <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                  <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Identifier">"Specific"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Element type specific properties"</v>
                  </o>
                  <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Identifier">"Actions"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Action definitions"</v>
                  </o>
                  <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Identifier">"Common"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Common properties"</v>
                  </o>
                  <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Identifier">"Times"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Time definitions"</v>
                  </o>
                </d2>
                <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                  <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">true</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <v n="Identifier">"Exclude"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Exclude this element from build"</v>
                  </o>
                  <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                    <v n="Identifier">"Parallel"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the branch to parallel mode"</v>
                  </o>
                  <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <v n="Identifier">"Name"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Name of the element"</v>
                  </o>
                  <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                    <v n="Identifier">"Duplication"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                  </o>
                  <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                    <v n="Identifier">"InitStep"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the step as the initial step"</v>
                  </o>
                  <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                    <v n="Identifier">"MainAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is active"</v>
                  </o>
                  <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">true</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <v n="Identifier">"Comment"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Comment of the element"</v>
                  </o>
                  <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                    <v n="Identifier">"Monitoring"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Indicates transition monitoring setting."</v>
                  </o>
                  <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                    <v n="Identifier">"ExitAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                  </o>
                  <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                    <v n="Identifier">"EntryAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is activated"</v>
                  </o>
                  <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                    <v n="Identifier">"MaxTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the maximal active time for the step"</v>
                  </o>
                  <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                    <v n="Identifier">"Symbol"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Symbol configuration setting of the element"</v>
                  </o>
                  <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                    <v n="Identifier">"MinTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the minimal active time for the step"</v>
                  </o>
                  <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                    <v n="Identifier">"Qualifier"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Qualifier of the action association"</v>
                  </o>
                </d2>
                <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                  <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                  <o>
                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Variable"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"Variable"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Call"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Call"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                  <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                  <o>
                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"Unspecified"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"Unspecified"</v>
                      </o>
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Read"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Read"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Write"</v>
                        <v n="Value">3L</v>
                        <v n="Key">"Write"</v>
                      </o>
                      <o>
                        <v n="Identifier">"ReadWrite"</v>
                        <v n="Value">4L</v>
                        <v n="Key">"ReadWrite"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                </d2>
                <v n="ImplId">1L</v>
              </o>
            </Data>
            <TypeList>
              <Type n="ArrayList">System.Collections.ArrayList</Type>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
              <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
              <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
              <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
              <Type n="Guid">System.Guid</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
              <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
              <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
              <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
              <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
              <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
              <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
              <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
              <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
              <Type n="String">System.String</Type>
              <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
            </TypeList>
          </XmlArchive>
        </SFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCProperty">
              <n n="SFCErrorAnalyzation" />
              <n n="SFCErrorAnalyzationTable" />
              <n n="SFCCurrentSteps" />
              <n n="SFCMetaSteps" />
              <v n="Title">"IecSfc"</v>
              <v n="Company">"System"</v>
              <v n="Version">"4.4.0.0"</v>
              <v n="Namespace">""</v>
              <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
                <v>EnableLimit</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Init</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Reset</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>QuitError</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Pause</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Error</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Trans</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorPOU</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Tip</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>TipMode</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzation</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzationTable</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentSteps</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
              </d2>
              <v n="CalcActiveTransOnly">false</v>
              <v n="UseDefaults">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
            <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
            <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="_aDrop_Cell_Rail1" Id="{4a9d4d90-45fb-4d7d-aad0-afa0f297d2d4}">
      <Implementation>
        <ST><![CDATA[Status := F_IssueActuatorCommand(sDevice := 'Chariot1', bArg := FALSE);

]]></ST>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="_aEnd_Homing" Id="{0dc240cc-031c-4364-9609-10d07dafd78b}">
      <Implementation>
        <ST><![CDATA[bHomingDone := TRUE;]]></ST>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="_aHoming_step_active" Id="{af655b4e-aa21-49ae-80b0-b983e3e6a8f9}">
      <Implementation>
        <SFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="SFCImplementationObject">
                <o n="Root" t="SFCSegment">
                  <o n="ElementList" t="SFCElementList">
                    <l2 n="InnerList">
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init_step"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">4L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">5L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">6L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">7L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">8L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">9L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">10L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">11L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_aInit_step_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">12L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">13L</v>
                            <v n="IdParent">3L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">14L</v>
                            <v n="IdParent">3L</v>
                          </o>
                        </l2>
                        <v n="Id">3L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Init_step__to___aHoming_Rail1_step"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"NOT bStopCycleMem AND FALSE"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">27L</v>
                            <v n="IdParent">26L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">28L</v>
                            <v n="IdParent">26L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">29L</v>
                            <v n="IdParent">26L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">30L</v>
                            <v n="IdParent">26L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">31L</v>
                            <v n="IdParent">26L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">32L</v>
                            <v n="IdParent">26L</v>
                          </o>
                        </l2>
                        <v n="Id">26L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_aHoming_Rail1_step"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">34L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">35L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">36L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">37L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">38L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">39L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">40L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">41L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_a_aHoming_Rail1_step_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">42L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">43L</v>
                            <v n="IdParent">33L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">44L</v>
                            <v n="IdParent">33L</v>
                          </o>
                        </l2>
                        <v n="Id">33L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"_aHoming_Rail1_step__to___aHoming_Rail2_step"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Status = 1 AND NOT bStopCycleMem"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">46L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">47L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">48L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">49L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">50L</v>
                            <v n="IdParent">45L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">51L</v>
                            <v n="IdParent">45L</v>
                          </o>
                        </l2>
                        <v n="Id">45L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_aHoming_Rail2_step"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">53L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">54L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">55L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">56L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">57L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">58L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">59L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">60L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_a_aHoming_Rail2_step_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">61L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">62L</v>
                            <v n="IdParent">52L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">63L</v>
                            <v n="IdParent">52L</v>
                          </o>
                        </l2>
                        <v n="Id">52L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"_aHoming_Rail2_step__to___aHoming_Rail3_step"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Status = 1 AND NOT bStopCycleMem"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">65L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">66L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">67L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">68L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">69L</v>
                            <v n="IdParent">64L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">70L</v>
                            <v n="IdParent">64L</v>
                          </o>
                        </l2>
                        <v n="Id">64L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_aHoming_Rail3_step"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">72L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">73L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">74L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">75L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">76L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">77L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">78L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">79L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_a_aHoming_Rail3_step_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">80L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">81L</v>
                            <v n="IdParent">71L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">82L</v>
                            <v n="IdParent">71L</v>
                          </o>
                        </l2>
                        <v n="Id">71L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"_aHoming_Rail3_step__to___aHoming_Rail4_step"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Status = 1 AND NOT bStopCycleMem"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">84L</v>
                            <v n="IdParent">83L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">85L</v>
                            <v n="IdParent">83L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">86L</v>
                            <v n="IdParent">83L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">87L</v>
                            <v n="IdParent">83L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">88L</v>
                            <v n="IdParent">83L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">89L</v>
                            <v n="IdParent">83L</v>
                          </o>
                        </l2>
                        <v n="Id">83L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_aHoming_Rail4_step"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">91L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">92L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">93L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">94L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">95L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">96L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">97L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">98L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"_a_aHoming_Rail4_step_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">99L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">100L</v>
                            <v n="IdParent">90L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">101L</v>
                            <v n="IdParent">90L</v>
                          </o>
                        </l2>
                        <v n="Id">90L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"_aHoming_Rail4_step__to__Init_step"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">16L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">17L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">18L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">19L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">20L</v>
                            <v n="IdParent">15L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">21L</v>
                            <v n="IdParent">15L</v>
                          </o>
                        </l2>
                        <v n="Id">15L</v>
                        <v n="IdParent">2L</v>
                      </o>
                      <o t="SFCJump">
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init_step"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">23L</v>
                            <v n="IdParent">22L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">24L</v>
                            <v n="IdParent">22L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">25L</v>
                            <v n="IdParent">22L</v>
                          </o>
                        </l2>
                        <v n="Id">22L</v>
                        <v n="IdParent">2L</v>
                      </o>
                    </l2>
                  </o>
                  <l2 n="Attributes" />
                  <v n="Id">2L</v>
                  <v n="IdParent">-1L</v>
                </o>
                <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                  <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Identifier">"Specific"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Element type specific properties"</v>
                  </o>
                  <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Identifier">"Actions"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Action definitions"</v>
                  </o>
                  <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Identifier">"Common"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Common properties"</v>
                  </o>
                  <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Identifier">"Times"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Time definitions"</v>
                  </o>
                </d2>
                <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                  <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">true</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <v n="Identifier">"Exclude"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Exclude this element from build"</v>
                  </o>
                  <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                    <v n="Identifier">"Parallel"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the branch to parallel mode"</v>
                  </o>
                  <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <v n="Identifier">"Name"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Name of the element"</v>
                  </o>
                  <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                    <v n="Identifier">"Duplication"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                  </o>
                  <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                    <v n="Identifier">"InitStep"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the step as the initial step"</v>
                  </o>
                  <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                    <v n="Identifier">"MainAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is active"</v>
                  </o>
                  <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">true</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <v n="Identifier">"Comment"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Comment of the element"</v>
                  </o>
                  <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                    <v n="Identifier">"Monitoring"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Indicates transition monitoring setting."</v>
                  </o>
                  <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                    <v n="Identifier">"ExitAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                  </o>
                  <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                    <v n="Identifier">"EntryAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is activated"</v>
                  </o>
                  <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                    <v n="Identifier">"MaxTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the maximal active time for the step"</v>
                  </o>
                  <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                    <v n="Identifier">"Symbol"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Symbol configuration setting of the element"</v>
                  </o>
                  <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                    <v n="Identifier">"MinTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the minimal active time for the step"</v>
                  </o>
                  <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                    <v n="Identifier">"Qualifier"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Qualifier of the action association"</v>
                  </o>
                </d2>
                <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                  <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                  <o>
                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Variable"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"Variable"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Call"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Call"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                  <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                  <o>
                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"Unspecified"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"Unspecified"</v>
                      </o>
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Read"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Read"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Write"</v>
                        <v n="Value">3L</v>
                        <v n="Key">"Write"</v>
                      </o>
                      <o>
                        <v n="Identifier">"ReadWrite"</v>
                        <v n="Value">4L</v>
                        <v n="Key">"ReadWrite"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                </d2>
                <v n="ImplId">1L</v>
              </o>
            </Data>
            <TypeList>
              <Type n="ArrayList">System.Collections.ArrayList</Type>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
              <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
              <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
              <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
              <Type n="Guid">System.Guid</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
              <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
              <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
              <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
              <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
              <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
              <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
              <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
              <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
              <Type n="String">System.String</Type>
              <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
            </TypeList>
          </XmlArchive>
        </SFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCProperty">
              <n n="SFCErrorAnalyzation" />
              <n n="SFCErrorAnalyzationTable" />
              <n n="SFCCurrentSteps" />
              <n n="SFCMetaSteps" />
              <v n="Title">"IecSfc"</v>
              <v n="Company">"System"</v>
              <v n="Version">"4.4.0.0"</v>
              <v n="Namespace">""</v>
              <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
                <v>EnableLimit</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Init</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Reset</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>QuitError</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Pause</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Error</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Trans</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorPOU</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Tip</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>TipMode</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzation</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzationTable</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentSteps</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
              </d2>
              <v n="CalcActiveTransOnly">false</v>
              <v n="UseDefaults">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
            <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
            <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="_aInit_step_active" Id="{6fbfe122-8bb2-4ca9-9f3c-6f967374eb7f}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="_aMove_Rail1" Id="{28b8c964-5b72-4ee3-a1ba-894fd8a3a263}">
      <Implementation>
        <ST><![CDATA[Status := F_IssueActuatorCommand(sDevice := 'Motor1', bArg := FALSE, bHasPosition := TRUE, nPosition := Rail1_Pos4);

]]></ST>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="ActionObjectDuplicationModeProperty">
              <v n="Embedded">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="ActionObjectDuplicationModeProperty">{6a58c9ae-b0e2-4127-8d9c-cbfc36a09580}</Type>
            <Type n="Boolean">System.Boolean</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="Init_active" Id="{10aa273c-50f4-48b2-827b-3d0220d77be7}">
      <Implementation>
        <ST><![CDATA[
RTrigStart(CLK := StartCycle);
RTrigStop (CLK := StopCycle);

(* If START is pressed -> remember START, forget STOP *)
IF RTrigStart.Q THEN
    bStartCycleMem := TRUE;
    bStopCycleMem  := FALSE;
END_IF

(* If STOP is pressed -> remember STOP, forget START *)
IF RTrigStop.Q THEN
    bStopCycleMem  := TRUE;
    bStartCycleMem := FALSE;
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="Init_Cycle_Megagenial_active" Id="{69ec266d-c837-4b14-90a1-9314bb16ec18}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="SFCProperty">
            <n n="SFCErrorAnalyzation" />
            <n n="SFCErrorAnalyzationTable" />
            <n n="SFCCurrentSteps" />
            <n n="SFCMetaSteps" />
            <v n="Title">"IecSfc"</v>
            <v n="Company">"System"</v>
            <v n="Version">"3.4.2.0"</v>
            <v n="Namespace">""</v>
            <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
              <v>EnableLimit</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Init</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Reset</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>QuitError</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Pause</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Error</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Trans</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorPOU</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>CurrentStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Tip</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>TipMode</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzation</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzationTable</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
            </d2>
            <v n="CalcActiveTransOnly">false</v>
            <v n="UseDefaults">true</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
          <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
          <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
          <Type n="String">System.String</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="PRG_Cycle._a_aHoming_Rail1_step_active">
      <LineId Id="1" Count="1" />
    </LineIds>
    <LineIds Name="PRG_Cycle._a_aHoming_Rail2_step_active">
      <LineId Id="1" Count="1" />
    </LineIds>
    <LineIds Name="PRG_Cycle._a_aHoming_Rail3_step_active">
      <LineId Id="1" Count="1" />
    </LineIds>
    <LineIds Name="PRG_Cycle._a_aHoming_Rail4_step_active">
      <LineId Id="1" Count="1" />
    </LineIds>
    <LineIds Name="PRG_Cycle._aCatch_Cell_Rail1">
      <LineId Id="1" Count="2" />
    </LineIds>
    <LineIds Name="PRG_Cycle._aDrop_Cell_Rail1">
      <LineId Id="1" Count="2" />
    </LineIds>
    <LineIds Name="PRG_Cycle._aEnd_Homing">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Cycle._aInit_step_active">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Cycle._aMove_Rail1">
      <LineId Id="1" Count="2" />
    </LineIds>
    <LineIds Name="PRG_Cycle.Init_active">
      <LineId Id="1" Count="15" />
    </LineIds>
    <LineIds Name="PRG_Cycle.Init_Cycle_Megagenial_active">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>